name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        - name: Set up Personal Access Token
  run: echo "PERSONAL_ACCESS_TOKEN=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" >> $GITHUB_ENV

      - name: Verify Personal Access Token
        run: |
          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "Error: PERSONAL_ACCESS_TOKEN is not set."
            exit 1
          fi
with:
  github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  publish_dir: ./build
      - name: Set up Personal Access Token
        run: echo "PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build
